### ISSUE TITLE
Geranium screen time issue 

### ISSUE THREAD

**Issue by Stealth70** [c22dev/Geranium#34]
Hello I am still experiencing issue as when I disable ‘com.apple.ScreentimeAgent,’and then I reboot my iPad  nothing happens please tell me a fix.

**Comment by Stealth70** [comment]
I have just tried that and I manually rebooted my device and I enabled family circle as it is iCloud screen time but it still won’t work.

**Comment by c22dev** [comment]
You only disabled familycircled?

**Comment by Stealth70** [comment]
No, I turned on family circle before clicking bye screen time and when I reboot my device nothing happens and when I check back family circle turns off by itself.

**Comment by c22dev** [comment]
It's normal for it to be toggled off.
Toggle them all on and try again.

**Comment by Stealth70** [comment]
Same issue.

**Comment by Stealth70** [comment]
I toggled all on, it didn't work.

**Comment by c22dev** [comment]
What device are you on ?
Do you have an iCloud ScreenTime ?

**Comment by Stealth70** [comment]
I am on iPad Pro 12.9 inch 5th gen iOS 16.6.
Yes I have iCloud screen time.

**Comment by c22dev** [comment]
Okay, weird then, it should work no issue
You could try restoring the daemon files in Daemon Management settings, reboot, then wait for like 5-10min, then re-reboot, then try again with byeTime.

**Comment by Stealth70** [comment]
Okay will try

**Comment by Stealth70** [comment]
Same issue when I reboot screen time is gone for about 5-10 seconds but after that screen time turns on again.

**Comment by Stealth70** [comment]
Is there any fix? If yes please tell me as soon as possible.

**Comment by c22dev** [comment]
No, as it works for most people.
I can't debug any further and I've ran out of ideas, sorry.

**Comment by Stealth70** [comment]
Then what should I do?

**Comment by Stealth70** [comment]
I need this to work.

**Comment by Stealth70** [comment]
Is there any other app that disables screen time as well?

**Comment by Stealth70** [comment]
Should I try install one of the older versions off the app?

**Comment by Stealth70** [comment]
Hello, I have noticed that it does disables the daemon com.apple.ScreenTimeAgent but for some odd reason it still doesn't work. Is it possible in the next update this could be fixed?

**Comment by c22dev** [comment]
**Commenting multiple times here won't get your issue fixed I'm afraid.**
### Here is a little Q&A for your numerous comments, hope it helps.

> Is it possible in the next update this could be fixed?

As I said, I don't have any intention to push an update any time soon related to your issue, simply because I can't reproduce it on my side and that I don't really understand what's going on (eh, iOS daemons are weird yk)
Nobody ever had an issue and most people got it to work after the manipulations I suggested you (I'm out of idea ngl + it's been so long I should get back to it to give you some real try and see tips)

> Then what should I do?

I could only encourage you to reset your iPad through Settings but I imagine it's not a viable option for you. See next section.

> Is there any other app that disables screen time as well?

I don't have any particular names in mind right now but I'm sure a quick search on Google will get you covered (or a Reddit post?). I guess there is maybe a jailbreak tweak out there that might help you.

> Should I try install one of the older versions of the app?

Old versions of the app won't change anything (and will only make it worse in my opinion). Don't !

**Comment by Stealth70** [comment]
Hello, thank you for your reply. Can you please tell me what jailbreak tweak it is?

**Comment by Stealth70** [comment]
If it's possible for me to get this issue fix by disabling the daemons manually through filza but I don't know anything about the app so I would need assistance from you.
